#
# pinout element and component attributes
# =======================================

diagram:
  tag: pinout

panel: 
  padding: [10, 10, 10, 10]
  fill: [244, 244, 244]
  fill_opacity: 1
  rx: 0
  stroke: [255, 255, 255]
  stroke_width: 1
  tag: panel__bg


text: &text
    fill: [0, 0, 0]
    family: Verdana, Geneva, sans-serif
    line_height: 20
    size: 14
    weight: normal



# information-panel
infpanel_rect: &infpanel
  fill: [244, 244, 244]
  stroke: [204, 204, 204]
  stroke_width: 0
  rx: 0

rect: &rect
  fill: [244, 244, 244]
  stroke: [204, 204, 204]
  stroke_width: 1
  rx: 0

path:
  stroke: [204, 204, 204]
  stroke_width: 3


label:
  rect:
    << : *rect
    height: 28
    width: 60
    rx: 4
    stroke_width: 1
  text: 
    << : *text


legend:
  row_height: 30
  tag: legend
  rect:
    << : *infpanel
    # height: dynamically calculated
    width: 300
  text:
    fill: [0,0,0]
    family: Verdana, Geneva, sans-serif
    size: 12
    weight: bold


pinlabel:
  offset: [8,0]
  tag: pl
  label:
    text:
      fill: [255,255,255]
      family: Verdana, Geneva, sans-serif
      size: 12
      weight: normal
    rect:
      fill: [0, 0, 0]
      height: 26
      rx: 2
      stroke: [204, 204, 204]
      stroke_width: 0
      width: 50
  leaderline:
    stroke: [204, 204, 204]
    stroke_width: 1
    tag: ll


pinlabelrow:
  tag: pl-row


leaderline:
  stroke: [204, 204, 204]
  stroke_width: 1
  tag: ll


informationpanel:
  tag: inf
  fill: [255,255,255]
  stroke: [225, 225, 225]
  stroke_width: 3
  rx: 4

annotation:
  offset: [50,-50]
  label:
    padding: [8, 8]
    text: 
      fill: [0, 0, 0]
      family: Verdana, Geneva, sans-serif
      line_height: 18
      size: 14
      weight: normal
    rect:
      fill: [246, 148, 30]
      fill_opacity: 0
      # height:  #Calculated automatically#
      rx: 0
      stroke: [246, 148, 30]
      stroke_width: 0
      width: 260
  leaderline:
    stroke: [246, 148, 30]
    stroke_width: 2
    rect:
      fill: [246, 148, 30]
      fill_opacity: 1
      stroke: [246, 148, 30]
      stroke_width: 2
      rx: 0
      width: 12
      height: 12



# Tag styleguide
# ================================
#
# <tag> tag identifier (must be CSS compliant name)
# <title> text representation in legend
# <color> RGB color representation
#
# tags:
#   <tag1>
#     title: <title>
#     color: [<0-255>, <0-255>, <0-255>]
#   <tag2>
#     title: <title>
#     color: [<0-255>, <0-255>, <0-255>]

